---
postgresql_packages:
  - postgresql-{{ postgresql_version }}
  - postgresql-client-{{ postgresql_version }}
  - postgresql-contrib-{{ postgresql_version }}
  - python3-psycopg2
postgresql_service_name: postgresql
postgresql_data_dir: /var/lib/postgresql/{{ postgresql_version }}/main
postgresql_conf_dir: /etc/postgresql/{{ postgresql_version }}/main
postgresql_listen_addresses: "{{ postgres_listen_addresses | join(',') }}"
postgresql_hba_allowed_subnets: "{{ postgresql_hba_allowed_subnets }}"
postgresql_shared_buffers: "{{ postgresql_shared_buffers }}"
postgresql_effective_cache_size: "{{ postgresql_effective_cache_size }}"
postgresql_maintenance_work_mem: "{{ postgresql_maintenance_work_mem }}"
postgresql_autovacuum_max_workers: {{ postgresql_autovacuum_max_workers }}
postgresql_wal_keep_size: "{{ postgresql_wal_keep_size }}"
postgresql_superuser: "{{ postgres_admin_user }}"
postgresql_superuser_password: "{{ postgres_admin_password }}"
postgresql_app_users: "{{ postgres_app_users }}"
postgres_port: 5432

