#!/usr/bin/env bash
set -euo pipefail

log() { printf '[dns-unbound-opnsense] %s\n' "$*"; }
err() { printf '[dns-unbound-opnsense][error] %s\n' "$*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CONFIG_FILE=""
RUNTIME_DIR_OVERRIDE=""
ZONE_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      CONFIG_FILE="${2:-}"
      shift 2
      ;;
    --runtime-dir)
      RUNTIME_DIR_OVERRIDE="${2:-}"
      shift 2
      ;;
    --zone)
      ZONE_OVERRIDE="${2:-}"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage: bootstrap/dns-unbound-opnsense.sh [--config FILE] [--runtime-dir DIR] [--zone ZONE]

Generates OPNsense/Unbound import artifacts based on the RALF DNS manifest:
- unbound-host-overrides.csv
- unbound-custom-options.conf

Outputs are written to: $RUNTIME_DIR/dns/
EOF
      exit 0
      ;;
    *)
      err "Unbekannte Option: $1"
      exit 2
      ;;
  esac
done

if [[ -z "$CONFIG_FILE" ]]; then
  CONFIG_FILE="$REPO_ROOT/bootstrap/bootstrap.env"
fi

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

RALF_DOMAIN="${RALF_DOMAIN:-otta.zone}"
RALF_DNS_ZONE="${ZONE_OVERRIDE:-${RALF_DNS_ZONE:-$RALF_DOMAIN}}"
RUNTIME_DIR="${RUNTIME_DIR_OVERRIDE:-${RUNTIME_DIR:-/opt/ralf/runtime}}"

DNS_DIR="$RUNTIME_DIR/dns"
HOSTS_FILE="$DNS_DIR/records.hosts"
CSV_FILE="$DNS_DIR/unbound-host-overrides.csv"
UNBOUND_FILE="$DNS_DIR/unbound-custom-options.conf"

mkdir -p "$DNS_DIR"

# Ensure source manifest exists and is up-to-date.
bash "$REPO_ROOT/bootstrap/dns-manifest.sh" --config "$CONFIG_FILE" --runtime-dir "$RUNTIME_DIR"

if [[ ! -f "$HOSTS_FILE" ]]; then
  err "DNS-Manifest nicht gefunden: $HOSTS_FILE"
  exit 1
fi

records=()
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  [[ "${line:0:1}" == "#" ]] && continue
  ip="${line%% *}"
  fqdn="${line##* }"
  records+=("$ip $fqdn")
done < "$HOSTS_FILE"

if [[ "${#records[@]}" -eq 0 ]]; then
  err "Keine DNS-Records im Manifest gefunden."
  exit 1
fi

{
  printf 'enabled,hostname,domain,server,description\n'
  for entry in "${records[@]}"; do
    ip="${entry%% *}"
    fqdn="${entry##* }"
    host="${fqdn%%.*}"
    domain="${fqdn#*.}"
    printf '1,%s,%s,%s,%s\n' "$host" "$domain" "$ip" "RALF internal service"
  done
} > "$CSV_FILE"

{
  printf '# Generated by bootstrap/dns-unbound-opnsense.sh\n'
  printf '# Zone: %s\n' "$RALF_DNS_ZONE"
  printf '# Timestamp: %s\n' "$(date -Iseconds)"
  printf '\n'
  printf 'server:\n'
  printf '  local-zone: "%s." static\n' "$RALF_DNS_ZONE"
  for entry in "${records[@]}"; do
    ip="${entry%% *}"
    fqdn="${entry##* }"
    printf '  local-data: "%s. IN A %s"\n' "$fqdn" "$ip"
  done
} > "$UNBOUND_FILE"

log "Host-Overrides CSV geschrieben: $CSV_FILE"
log "Unbound Custom-Options geschrieben: $UNBOUND_FILE"
log "Hinweis: In OPNsense unter Services -> Unbound DNS importieren/einfuegen und Unbound neu laden."
