#!/usr/bin/env bash
set -euo pipefail

log() { printf '[dns-manifest] %s\n' "$*"; }
err() { printf '[dns-manifest][error] %s\n' "$*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CONFIG_FILE=""
RUNTIME_DIR_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      CONFIG_FILE="${2:-}"
      shift 2
      ;;
    --runtime-dir)
      RUNTIME_DIR_OVERRIDE="${2:-}"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage: bootstrap/dns-manifest.sh [--config FILE] [--runtime-dir DIR]

Generates DNS manifests for the internal RALF zone:
- hosts-style file
- BIND zone snippet

Outputs are written to: $RUNTIME_DIR/dns/
EOF
      exit 0
      ;;
    *)
      err "Unbekannte Option: $1"
      exit 2
      ;;
  esac
done

if [[ -z "$CONFIG_FILE" ]]; then
  CONFIG_FILE="$REPO_ROOT/bootstrap/bootstrap.env"
fi

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

RALF_DOMAIN="${RALF_DOMAIN:-otta.zone}"
RALF_DNS_ZONE="${RALF_DNS_ZONE:-$RALF_DOMAIN}"
RUNTIME_DIR="${RUNTIME_DIR_OVERRIDE:-${RUNTIME_DIR:-/opt/ralf/runtime}}"

DNS_DIR="$RUNTIME_DIR/dns"
HOSTS_FILE="$DNS_DIR/records.hosts"
ZONE_FILE="$DNS_DIR/zone.bind"

mkdir -p "$DNS_DIR"

# Canonical MVP records based on docs/IP-KONVENTION.md
services=(
  "postgresql 10.10.20.10"
  "minio 10.10.30.10"
  "gitea 10.10.40.10"
  "vaultwarden 10.10.50.10"
  "prometheus 10.10.80.10"
  "ki 10.10.90.10"
  "semaphore 10.10.100.10"
  "n8n 10.10.100.20"
  "matrix 10.10.110.10"
)

{
  printf '# Generated by bootstrap/dns-manifest.sh\n'
  printf '# Zone: %s\n' "$RALF_DNS_ZONE"
  printf '# Timestamp: %s\n' "$(date -Iseconds)"
  printf '\n'
  for entry in "${services[@]}"; do
    name="${entry%% *}"
    ip="${entry##* }"
    printf '%s %s.%s\n' "$ip" "$name" "$RALF_DNS_ZONE"
  done
} > "$HOSTS_FILE"

serial="$(date +%Y%m%d%H)"
{
  printf '; Generated by bootstrap/dns-manifest.sh\n'
  printf '; Zone: %s\n' "$RALF_DNS_ZONE"
  printf '; Timestamp: %s\n' "$(date -Iseconds)"
  printf '\n'
  printf '$TTL 300\n'
  printf '@ IN SOA ns1.%s. hostmaster.%s. (\n' "$RALF_DNS_ZONE" "$RALF_DNS_ZONE"
  printf '  %s ; serial\n' "$serial"
  printf '  300 ; refresh\n'
  printf '  120 ; retry\n'
  printf '  604800 ; expire\n'
  printf '  300 ; minimum\n'
  printf ')\n'
  printf '@ IN NS ns1.%s.\n' "$RALF_DNS_ZONE"
  printf '\n'
  for entry in "${services[@]}"; do
    name="${entry%% *}"
    ip="${entry##* }"
    printf '%s IN A %s\n' "$name" "$ip"
  done
} > "$ZONE_FILE"

log "DNS-Manifest geschrieben: $HOSTS_FILE"
log "BIND-Zone geschrieben: $ZONE_FILE"
