---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: vaultwarden_manage_systemd | bool

- name: Restart vaultwarden service
  ansible.builtin.systemd:
    name: vaultwarden.service
    state: restarted
    enabled: true
  when: vaultwarden_manage_systemd | bool

- name: Restart vaultwarden backup timer
  ansible.builtin.systemd:
    name: vaultwarden-backup.timer
    state: restarted
    enabled: true
  when: vaultwarden_manage_systemd | bool
