all:
  children:
    proxmox:
      hosts:
        pve0:
          ansible_host: 10.23.10.10
        pve1:
          ansible_host: 10.23.10.11
        pve2:
          ansible_host: 10.23.10.12
    core:
      hosts:
        dns01:
          ansible_host: 10.23.20.10
        caddy01:
          ansible_host: 10.23.20.20
        auth01:
          ansible_host: 10.23.20.30
        mon01:
          ansible_host: 10.23.20.40
        backup01:
          ansible_host: 10.23.30.10
    services:
      hosts:
        vaultwarden01:
          ansible_host: 10.23.20.50
        mail01:
          ansible_host: 10.23.20.60
        homeassistant01:
          ansible_host: 10.23.20.70
