all:
  children:
    proxmox:
      hosts:
        pve0:
          ansible_host: 10.23.10.10
        pve1:
          ansible_host: 10.23.10.11
        pve2:
          ansible_host: 10.23.10.12
    core:
      hosts:
        dns01:
          ansible_host: 10.23.20.10
        caddy01:
          ansible_host: 10.23.20.20
        auth01:
          ansible_host: 10.23.20.30
        mon01:
          ansible_host: 10.23.20.40
        backup01:
          ansible_host: 10.23.30.10
    services:
      hosts:
        vaultwarden01:
          ansible_host: 10.23.20.50
        mail01:
          ansible_host: 10.23.20.60
        homeassistant01:
          ansible_host: 10.23.20.70
        n8n01:
          ansible_host: 10.23.20.80
        synapse01:
          ansible_host: 10.23.20.90
        elementweb01:
          ansible_host: 10.23.20.100
    toolchain:
      hosts:
        gitea01:
          ansible_host: 10.23.40.10
        jenkins01:
          ansible_host: 10.23.40.20
        semaphore01:
          ansible_host: 10.23.40.30
        foreman01:
          ansible_host: 10.23.40.40
        opentofu01:
          ansible_host: 10.23.40.50
        postgresql01:
          ansible_host: 10.23.40.60
