---
opentofu_version: 1.8.3
opentofu_download_url: "https://github.com/opentofu/opentofu/releases/download/v{{ opentofu_version }}/tofu_{{ opentofu_version }}_linux_amd64.zip"
opentofu_install_path: /usr/local/bin/tofu
