---
# Default variables for the Foreman role
foreman_packages:
  - foreman-installer
foreman_config_path: /etc/foreman/settings.yaml
foreman_user: root
foreman_group: root
foreman_admin_user: admin
foreman_admin_password: changeme
foreman_url: https://foreman.example.lan
