---
# Default variables for the Semaphore role
semaphore_packages:
  - semaphore
semaphore_config_path: /etc/semaphore/config.json
semaphore_user: root
semaphore_group: root
semaphore_listen_port: 3000
semaphore_db_host: 127.0.0.1
semaphore_db_port: 5432
