---
- name: Reload prometheus service
  community.docker.docker_compose:
    project_src: "{{ monitoring_base_dir }}"
    project_name: "{{ monitoring_compose_project_name }}"
    services:
      - prometheus
    state: present
    restarted: true
  when: monitoring_manage_docker

- name: Restart alertmanager service
  community.docker.docker_compose:
    project_src: "{{ monitoring_base_dir }}"
    project_name: "{{ monitoring_compose_project_name }}"
    services:
      - alertmanager
    state: present
    restarted: true
  when: monitoring_manage_docker

- name: Restart grafana service
  community.docker.docker_compose:
    project_src: "{{ monitoring_base_dir }}"
    project_name: "{{ monitoring_compose_project_name }}"
    services:
      - grafana
    state: present
    restarted: true
  when: monitoring_manage_docker

- name: Restart node-exporter service
  community.docker.docker_compose:
    project_src: "{{ monitoring_base_dir }}"
    project_name: "{{ monitoring_compose_project_name }}"
    services:
      - node-exporter
    state: present
    restarted: true
  when: monitoring_manage_docker
