#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/common.sh"

PLAN=""
INV=""
PLAN="/root/ralf/plan.json"
INV="/root/ralf/inventory.json"

ctid_of(){ jq -r ".services[\"$1\"].ctid" "$PLAN"; }
ip_of(){ jq -r --arg n "$1" '.[$n].ip // empty' "$INV"; }
fqdn_of(){ jq -r ".services[\"$1\"].fqdn" "$PLAN"; }
exp_of(){ jq -r ".services[\"$1\"].exposure" "$PLAN"; }

install_caddy(){
  local ct=$(ctid_of ralf-edge)
  echo "[*] ralf-edge (#$ct): Caddy Reverse Proxy"
  pct exec "$ct" -- bash -lc "apt-get update -y && apt-get install -y debian-keyring debian-archive-keyring curl apt-transport-https"
  pct exec "$ct" -- bash -lc "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | tee /etc/apt/trusted.gpg.d/caddy-stable.asc >/dev/null"
  pct exec "$ct" -- bash -lc "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list"
  pct exec "$ct" -- bash -lc "apt-get update -y && apt-get install -y caddy"
}

gen_caddyfile(){
  local base_domain=$(jq -r '.domain.base_domain' "$PLAN")
  local acme_mail=$(jq -r '.domain.acme_email' "$PLAN")
  local has_pub=$(jq -r '.domain.has_public_domain' "$PLAN")

  local cf="/tmp/Caddyfile"
  echo "# Auto-generated by RALF" > "$cf"
  if [[ "$has_pub" == "true" ]]; then
    echo "(tls-le) {" >> "$cf"
    echo "  tls ${acme_mail}" >> "$cf"
    echo "}" >> "$cf"
  else
    echo "(tls-le) {" >> "$cf"
    echo "  tls internal" >> "$cf"
    echo "}" >> "$cf"
  fi

  for svc in ralf-gitea ralf-netbox ralf-n8n ralf-matrix ralf-secrets ralf-foreman; do
    local exp=$(exp_of $svc)
    local fqdn=$(fqdn_of $svc)
    local ip=$(ip_of $svc)
    local target=""
    case "$svc" in
      ralf-gitea)   target="http://${ip}:3000";;
      ralf-netbox)  target="http://${ip}";;
      ralf-n8n)     target="http://${ip}:5678";;
      ralf-matrix)  target="http://${ip}:8008";;
      ralf-secrets) target="http://${ip}:8080";;
      ralf-foreman) target="https://${ip}";;
    esac

    echo "${fqdn} {" >> "$cf"
    if [[ "$exp" == "public" ]]; then
      echo "  import tls-le" >> "$cf"
    else
      echo "  tls internal" >> "$cf"
    fi
    echo "  reverse_proxy ${target}" >> "$cf"
    echo "}" >> "$cf"
  done
  echo "$cf"
}

apply_caddyfile(){
  local ct=$(ctid_of ralf-edge)
  local cf=$(gen_caddyfile)
  pct push "$ct" "$cf" "/etc/caddy/Caddyfile"
  pct exec "$ct" -- bash -lc "systemctl reload caddy || systemctl restart caddy"
}

main(){
  PLAN=$(jq -r '.plan_path' "$CONFIG_FILE")
  INV=$(jq -r '.inventory_path' "$CONFIG_FILE")
  install_caddy
  apply_caddyfile
  echo "[*] Caddy konfiguriert."
}
main "$@"
