version: "3.9"

services:
  infra:
    image: alpine:3.19
    container_name: ralf_a_infra
    command: ["/bin/sh", "-c", "apk add --no-cache ansible-core openssh && sleep infinity"]
    environment:
      AGENT_NAME: "A_INFRA"
      LOG_LEVEL: "debug"
      GITEA_URL: "http://gitea:3000"
      VAULTWARDEN_URL: "http://vaultwarden:80"
      AUTOMATION_QUEUE: "redis://runner-queue:6379/0"
    volumes:
      - infra_playbooks:/opt/ralf/playbooks
    networks:
      - ralf_testing

  gitea:
    image: gitea/gitea:1.21.10
    environment:
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__database__DB_TYPE: "sqlite3"
    volumes:
      - gitea_data:/data
    networks:
      - ralf_testing

  vaultwarden:
    image: vaultwarden/server:1.29.2
    environment:
      ROCKET_PORT: "80"
    volumes:
      - vaultwarden_data:/data
    networks:
      - ralf_testing

  runner-queue:
    image: redis:7-alpine
    networks:
      - ralf_testing

volumes:
  infra_playbooks:
  gitea_data:
  vaultwarden_data:

networks:
  ralf_testing:
    name: ralf_testing
    driver: bridge
