version: "3.9"

services:
  security:
    image: alpine:3.19
    container_name: ralf_a_sec
    command: ["/bin/sh", "-c", "apk add --no-cache curl clamav-daemon && freshclam && sleep infinity"]
    environment:
      AGENT_NAME: "A_SEC"
      LOG_LEVEL: "debug"
      VAULTWARDEN_URL: "http://vaultwarden:80"
      POLICY_REPO_URL: "http://gitea:3000/ralf/policies.git"
      ALERT_CHANNEL: "matrix://example-room"
    networks:
      - ralf_testing

  vaultwarden:
    image: vaultwarden/server:1.29.2
    environment:
      ROCKET_PORT: "80"
    volumes:
      - vaultwarden_data:/data
    networks:
      - ralf_testing

  auditlog:
    image: fluent/fluent-bit:2.2.2
    environment:
      FLUENT_BIT_LOG_LEVEL: "info"
    networks:
      - ralf_testing

volumes:
  vaultwarden_data:

networks:
  ralf_testing:
    name: ralf_testing
    driver: bridge
