#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage: $0 [--bootstrap] [--apply] [--skip-age]

Interactive bootstrap assistant for RALF 0.2. Prompts for core variables,
ensures age keys exist, writes vars to ./vars/, and optionally triggers
`make bootstrap` and `make apply`.

  --bootstrap   Run `make bootstrap` after writing configuration
  --apply       Run `make apply` after bootstrap (implies --bootstrap)
  --skip-age    Do not attempt to generate a new age keypair
  -h, --help    Show this message
USAGE
}

run_bootstrap=0
run_apply=0
skip_age=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bootstrap)
      run_bootstrap=1
      shift
      ;;
    --apply)
      run_bootstrap=1
      run_apply=1
      shift
      ;;
    --skip-age)
      skip_age=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

prompt() {
  local prompt_text="$1"
  local default_value="$2"
  local var
  read -r -p "$prompt_text [$default_value]: " var || true
  if [[ -z "$var" ]]; then
    printf '%s' "$default_value"
  else
    printf '%s' "$var"
  fi
}

mkdir -p vars secrets/age-keys

fqdn=$(prompt "Base domain (FQDN)" "homelab.lan")
network_cidr=$(prompt "Private network CIDR" "10.23.0.0/16")
vlan_mgmt=$(prompt "VLAN ID for management" "10")
vlan_services=$(prompt "VLAN ID for services" "20")
vlan_storage=$(prompt "VLAN ID for storage" "30")
vlan_dmz=$(prompt "VLAN ID for dmz" "40")
proxmox_host=$(prompt "Proxmox API host" "pve0.homelab.lan")
proxmox_user=$(prompt "Proxmox API user" "root@pam")
proxmox_token_id=$(prompt "Proxmox API token ID (user@realm!token)" "root@pam!ralf-bootstrap")
proxmox_token_secret=$(prompt "Proxmox API token secret (will be encrypted)" "changeme")
admin_email=$(prompt "Admin e-mail" "admin@${fqdn}")
matrix_domain=$(prompt "Matrix homeserver domain" "matrix.${fqdn}")
matrix_admin=$(prompt "Matrix admin username" "matrix-admin")
matrix_bot=$(prompt "Provision Matrix bot user" "ralf-bot")
backup_target=$(prompt "Backup dataset/path" "/rpool/backup")
image_distro=$(prompt "Golden image base distro" "debian-bookworm")
notifications=$(prompt "Notification target (mail/matrix/both)" "matrix")

vars_file="vars/ralf-installer.yaml"
cat > "$vars_file" <<YAML
# Autogenerated by scripts/ralf-installer.sh
fqdn: ${fqdn}
network_cidr: ${network_cidr}
vlan_ids:
  mgmt: ${vlan_mgmt}
  services: ${vlan_services}
  storage: ${vlan_storage}
  dmz: ${vlan_dmz}
proxmox:
  host: ${proxmox_host}
  user: ${proxmox_user}
  token_id: ${proxmox_token_id}
admin_email: ${admin_email}
matrix:
  domain: ${matrix_domain}
  admin_user: ${matrix_admin}
  bot_user: ${matrix_bot}
backups:
  target: ${backup_target}
images:
  distro: ${image_distro}
notifications: ${notifications}
YAML

echo "[installer] Wrote ${vars_file}"

if (( ! skip_age )); then
  age_key="secrets/age-keys/ralf.agekey"
  if [[ -f "$age_key" ]]; then
    echo "[installer] Existing age key detected at ${age_key}"
  else
    if command -v age-keygen >/dev/null 2>&1; then
      age-keygen -o "$age_key"
      chmod 600 "$age_key"
      echo "[installer] Generated new age key at ${age_key}"
      if command -v age-keygen >/dev/null 2>&1; then
        public_key=$(age-keygen -y "$age_key")
        echo "[installer] Public age key: ${public_key}"
        echo "[installer] Update secrets/.sops.yaml with the new public key."
      fi
    else
      echo "[installer] age-keygen not found; skipping key generation." >&2
    fi
  fi
fi

secrets_file="vars/ralf-secrets.yaml"
cat > "$secrets_file" <<YAML
# Encrypt this file with sops before committing.
proxmox_api_token_secret: ${proxmox_token_secret}
matrix_admin_password: changeme
matrix_bot_password: changeme-bot
YAML

echo "[installer] Wrote secrets scaffold to ${secrets_file}"

if command -v sops >/dev/null 2>&1; then
  if sops --encrypt --in-place "$secrets_file" 2>/dev/null; then
    echo "[installer] Encrypted ${secrets_file} with sops"
  else
    echo "[installer] sops available but encryption failed; leaving plaintext for review." >&2
  fi
else
  echo "[installer] sops not found; remember to encrypt ${secrets_file}." >&2
fi

if (( run_bootstrap )); then
  echo "[installer] Running make bootstrap"
  make bootstrap
fi

if (( run_apply )); then
  echo "[installer] Running make apply"
  make apply
fi

echo "[installer] Completed. Review vars/ and update inventory/network manifests as needed."
