---
creation_rules:
  - path_regex: ansible/group_vars/.*\.enc\.yml$
    encrypted_regex: '^(data$|secrets$|.*_secret$|.*_password$|.*_token$)'
    age: []
    shamir_threshold: 1
    pgp: []
  - path_regex: secrets/.*
    age: []
    pgp: []
# Füge deinen age-Recipient zur Laufzeit hinzu, z. B.:
# age: ["age1examplechangeme"]
