creation_rules:
  - path_regex: ansible/group_vars/.*\.enc\.yml$
    encrypted_regex: '^(data$|secrets$|.*_secret$|.*_password$|.*_token$)'
    age: age1dhl426fj0xz3cja3gm9avvqmt8e0efmr24xtzejwyzjyqd3kxpdquyfgqf
  - path_regex: secrets/.*
    age: age1dhl426fj0xz3cja3gm9avvqmt8e0efmr24xtzejwyzjyqd3kxpdquyfgqf

# Alters Schlüsselmaterial liegt unter secrets/keys/ralf-age-key.txt und wird
# via SOPS_AGE_KEY_FILE eingebunden.
